name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - Dockerfile
  pull_request:
    branches: [ "master" ]
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
      id: changed_files
  
    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        tags: |
            ghcr.io/dza89/resume-cli:latest
        push: ${{ github.ref == 'refs/heads/master' }}
